var FASHION = "" +
"WHOS WEARING WHAT AND WHERE THIS WEEK SEE WHO ROCKED IT ON THE RED CARPET AND " +
"WHOSE STREET STYLE WERE CRUSHING IN OUR WEEKLY EDIT OF BEST DRESSED STARS " +
"YESTERDAY BURBERRY HOSTED ONE OF THE MOST STARSTUDDED CATWALK SHOWS WEVE SEEN " +
"IN A LONG TIME HELD IN LA THE EVENT SAW MOST OF LONDON AND HOLLYWOOD COMBINE TO " +
"WATCH THE ACTION CLOTHES WERE MODELLED BY THE BRIT PACK MOST NOTABLY THE LEGEND " +
"NAOMI CAMPBELL AND THE BECKHAMS CARA DELEVINGNE ANNA WINTOUR AND ROSIE " +
"HUNTINGTONWHITELY WERE SAT FROM ROW TO SUPPORT CREATIVE DIRECTOR CHRISTOPHER " +
"BAILEY WHAT MADE YOU WANT TO DO A SHOE LINE NOW I HAVE ALWAYS BEEN ATTRACTED TO " +
"FASHION THAT IS TRANSITIONAL WEAR MEANING DESIGNS THAT CARRY A WOMAN FROM " +
"SEASON TO SEASON FROM DAY TO NIGHT THAT WAS A SIGNIFICANT PART OF THE THOUGHT " +
"PROCESS FOR THIS COLLECTION I WANTED TO THINK ABOUT FOOTWEAR THAT IS " +
"DIRECTIONAL AND ALSO COMFORTABLE I LIKE MY SHOES TO HAVE A BIT OF PERSONALITY " +
"WHY WAS MATISSE A GOOD PARTNER FOR YOU WE WERE INTRODUCED BY A MUTUAL FRIEND " +
"AND FELT WE WOULD WORK WELL TOGETHER ALL COLLABORATIONS I HAVE BEEN INVOLVED " +
"WITH STARTED ORGANICALLY THERE MUST BE A COMMON GOAL IN MIND TO UNDERSTAND AND " +
"APPRECIATE THE PERSON WE ARE DESIGNING FOR MATISSE IS SUCCESSFUL AT " +
"UNDERSTANDING THEIR CUSTOMER BUT WAS ALSO LOOKING FOR SOMEONE TO BRING A " +
"DIFFERENT PERSPECTIVE AT A SLIGHTLY HIGHER PRICE POINT I FELT I COULD HELP THEM " +
"ACHIEVE THIS VISION WHAT WAS THE INSPIRATION FOR THE COLLECTION I FIND " +
"INSPIRATION IN MANY THINGS FROM ART TO FILM TO WHAT IS RELEVANT IN FASHION " +
"CURRENTLY OR WHAT I WOULD LIKE TO SEE COME BACK AROUND AND FROM MY OWN LIFE " +
"EXPERIENCES ONE OF MY FAVORITE ARTISTS IS ED RUSCHA HIS HOT SHOT PIECE BECAME " +
"MY MAIN INSPIRATION FOR THE HOYT THE DAWN STYLE IS SLIGHTLY SURF INSPIRED WE " +
"UTILIZED NEOPRENE AND IS A NOD TO MY BLUE CRUSH DAYS ARE THERE ANY GIRLS WHO " +
"INSPIRE YOU LOTS OF THEM I LOVE SEEING GIRLS WHO FEEL CONFIDENT WITH THEMSELVES " +
"AND EMBRACE THEIR INDIVIDUALITY MY STEPDAUGHTER JASPER IS ONE WHATS YOUR DESIGN " +
"PROCESS LIKE INITIALLY I BROUGHT IN A VARIETY OF IMAGES TO DICTATE THE MOOD FOR " +
"AN OVERALL SCOPE OF THE COLLECTION THOUGH THERE ARE ONLY ABOUT  STYLES IN THIS " +
"COLLABORATION I KNEW I WANTED IT TO FEEL DIVERSE MY OWN STYLE CAN VARY FROM " +
"BOHEMIAN TO SPORTY TO MINIMALIST I WANTED TO TRANSLATE THIS KALEIDOSCOPIC FEEL " +
"INTO THE COLLECTION IN THIS SENSE THERE IS SOMETHING THAT CAN APPEAL TO MANY " +
"DIFFERENT WOMEN MOODS AND STYLE OF DRESS ONCE WE KNEW THE SHAPES OF THE SHOES " +
"WE DECIDED ON MATERIAL METALS AND EMBELLISHMENTS ONCE THESE DECISIONS ARE MADE " +
"AND THE DESIGNS ARE LOCKED THE SAMPLING PROCESS BEGINS AND AMENDMENTS ARE MADE " +
"WHEN NECESSARY HOW WILL YOU PERSONALLY STYLE THEM I WANTED TO CREATE SHAPES " +
"THAT ARE VERSATILE AND CAN BE WORN IN MANY WAYS I CAN WEAR THE KELLY STRAPPY " +
"SANDAL WITH DENIM SILK SHORTS OR A LITTLE SUMMER DRESS THE BOOTIES CAN BE WORN " +
"IN A MORE FOLKINSPIRED MANNER PAIRED WITH A LONG SKIRT ID LOVE TO SEE THE DAWN " +
"SPORTY SANDAL WORKS WITH A LONG BLACK SLIP DRESSTO BALANCE THE FEMININITY OF " +
"THE DRESS WITH A SPORTIER SHOE KARL LAGERFELD IS THE LATEST TO ACCESSORIZE WITH " +
"THE NEW APPLE WATCHONLY HIS IS CUSTOMMADE OF COURSE THE KAISER STYLED THE SOLID " +
"GOLD LINK WATCH WITH HIS SIGNATURE GLOVES NATURALLY IN AN INSTAGRAM SNAPPED BY " +
"ASSISTANT SEBASTIEN JONDEAU IF YOU HAD ANY DOUBTS ABOUT THE NEW WEARABLE TECH " +
"BEFORE THIS DEFINITELY CEMENTS ITS FASHION STATUS WITH ONLY TWO WEEKS UNTIL THE " +
"HIGHLY COVETED APPLE WATCH MAKES ITS OFFICIAL DEBUT THE NEW WEARABLE TECH IS " +
"ALREADY POPPING UP ON THE WRISTS OF CELEBRITIES CHRISTIE TURLINGTONBURNS " +
"SPORTED HER NEW WRIST CANDY WHILE PREPPING FOR THE LONDON MARATHON WHILE KATY " +
"PERRY SHARED A SNAP OF HER PLAYFUL NEW MICKEY MOUSE STYLE WATCHACTING AS THE " +
"FIRST REALLIFE MODELS OF THE NEW APPLE TECH PIECE THE SUPERMODEL OFFICIALLY " +
"RETIRES FROM THE CATWALK AFTER YEARS AND AN ABSOLUTELY LEGENDARY CAREER GISELE " +
"BNDCHEN IS SAYING FAREWELL TO THE CATWALK FOREVER GISELE IS CONSIDERED ONE OF " +
"THE MOST SUCCESSFUL AND CELEBRATED SUPERMODELS OF ALL TIME FORBES ESTIMATED HER " +
"EARNINGS AT MILLION WHICH INCLUDES INCOME FROM MODELING CONTRACTS AND NUMEROUS " +
"ENDORSEMENT DEALS RUMORS OF GISELES RETIREMENT HAVE BEEN FLOATING FOR QUITE " +
"SOME TIME NOW BUT ON WEDNESDAY SHE PERSONALLY CONFIRMED THE NEWS TO HER FANS ON " +
"INSTAGRAM SHE ANNOUNCED THAT WEDNESDAY EVENING HER APPEARANCE AT THE COLCCI " +
"SHOW DURING SAO PAULO FASHION WEEK WOULD BE HER LAST EVER FASHION SHOW I AM " +
"GRATEFUL THAT AT I WAS GIVEN THE OPPORTUNITY TO START THIS JOURNEY WROTE GISELE " +
"WHO IS MARRIED TO NFL STAR TOM BRADY AND HAS TWO CHILDREN BENJAMIN  AND VIVIAN " +
"TODAY AFTER YEARS IN THE INDUSTRY IT IS A PRIVILEGE TO BE DOING MY LAST " +
"FASHION SHOW BY CHOICE AND YET STILL BE WORKING IN OTHER FACETS OF THE BUSINESS " +
"IN AN INTERVIEW WITH FOLHA DE SAO PAULO VIA YAHOO GISELE SAID HER BODY TOLD HER " +
"IT WAS TIME TO STOP AUTOMATICALLY MY BODY TELLS ME IF WHAT I DO IS WORTH IT AND " +
"IT ASKED TO STOP I RESPECT MY BODY ITS A PRIVILEGE TO BE ABLE TO STOP RUNWAY " +
"WORK SHE SAID FANS CAN LOOK FORWARD TO THE FACT THAT GISELE ISNT WALKING WAY " +
"FROM FASHION ALTOGETHER SHES JUST LEAVING THE RUNWAY TO FOCUS ON MORE PROJECTS " +
"SHE HAS PLANNED FOR THE FUTURE I DONT SEE HOW TO CONTINUE RUNWAY MODELING " +
"GISELE SAID STOPPING WILL LEAVE ROOM FOR OTHER PROJECTS I HAVE FOR MYSELF ON " +
"HER LAST DAY ON THE CATWALK HER SPIRITS SEEMED HIGH SHE EVEN POSTED A " +
"BEHINDTHESCENES PIC FOR FANS AS SHE TOOK HER LAST FEW STRUTS HER FELLOW RUNWAY " +
"MODELS APPLAUDED HER AND WITH THAT GISELE SAID GOODBYE TO RUNWAY MODELING " +
"";

var NIHILISM = "ALTHOUGH NIHILISM IS OFTEN THOUGHT OF AS A VAGUE CONCEPT RELEGATED TO THE ARENA OF PHILOSOPHY OR PERHAPS AS THE UNAVOIDABLE CONCLUSION TO THOUGHT NIHILISM DOES HAVE A STRONG HISTORICAL BACKGROUND THAT DESERVES GREATER THE MOST SIGNIFICANT MANIFESTATION OF NIHILISM IN RECENT HISTORY ALSO COINCIDES WITH ITS MOST ACTIVE AND ORGANIZED EXPRESSION THAT OF THE RUSSIAN NIHILIST REVOLUTIONARIES WHO ROSE TO PROMINENCE IN THE THE RUSSIAN NIHILISTS THE RUSSIAN WORD FOR NIHILIST IS NIGILIST TEND TO BE ASSOCIATED WITH VIOLENCE REVOLUTION AND TERRORIST ACTS SUCH AS THE ASSASSINATION OF CZAR ALEXANDER II BY THE WILL OF THE PEOPLE BY ILYA REPIN BUT ALTHOUGH VIOLENT ACTS GET RECORDED IN THE HISTORY BOOKS OFTEN THE LASTING IMPACT IS CARRIED THROUGH IDEAS AND THE RUSSIAN NIHILISTS WERE INTRIGUING IN THIS REGARD FOR THEIR HISTORY IS LIKE THAT OF AN ICEBERG ONLY A SMALL PORTION OF THEIR TOTAL CHARACTER IS READILY INDEED MUCH OF THE VIOLENT ACTS ASSOCIATED WITH THE ATTEMPTED OVERTHROW OF THE MONARCHY OCCURRED UNDER THE AUSPICES OF OTHER GROUPS SUCH AS ANARCHISTS MARXISTS AND NARODNICHESTVO POPULISTS IN THE RATHER THAN THOSE DIRECTLY ASSOCIATED WITH THE NIHILISTS THEMSELVES WHO WERE MUCH MORE COMPLEX THAN THE TERRORIST LABEL ATTACHED TO THEM BY AUTOCRATIC NIHILISM WAS NOT SO MUCH A CORPUS OF FORMAL BELIEFS AND PROGRAMS LIKE POPULISM LIBERALISM MARXISM AS IT WAS A CLUSTER OF ATTITUDES AND SOCIAL VALUES AND A SET OF BEHAVIORAL DRESS FRIENDSHIP IN SHORT IT WAS AN IN ORDER TO UNDERSTAND WHO THE RUSSIAN NIHILISTS WERE WE FIRST HAVE TO UNDERSTAND WHAT THEY FOUGHT AGAINST AND EUROPE IN THE CENTURY WAS A TIME OF DRAMATIC CHANGES POLITICAL ECONOMIC AND INDUSTRIALIZATION CREATED FANTASTIC WEALTH DISPARITIES AND ENTIRELY NEW CLASSES OF PEOPLE AS THE OLD ARISTOCRATIC POWER SYSTEM TRANSFORMED INTO A PLUTOCRATIC CITIES GREW RAPIDLY AND TRADITIONAL AGRARIAN LIFESTYLES WERE DECIMATED IN FAVOR OF THE CRAMPED URBAN LIFE OF WAGE IMPERIAL RUSSIA EXPERIENCED MANY OF THESE DIFFICULT CHANGES BUT EVENTS OFTEN TOOK ON A MORE EXTREME CHARACTER THAN THAT OF WESTERN EUROPE AND SOCIAL DEVELOPMENT FOR RUSSIA HAS ALWAYS BEEN BOTH PAINFUL AND PUTTING A PROPAGANDIST UNDER ARREST BY ILYA REPIN OF THE WISER RUSSIAN MONARCHS REALIZED THAT THEIR SYSTEM OF SERFDOM WITH A SOCIAL STRUCTURE OF THE VERY FEW EXISTING ON THE BACKS OF THE VERY MANY WAS NOT SUSTAINABLE AND WOULD END IN BLOODY REBELLION SOONER OR THE PROBLEM WAS IMPLEMENTING REFORMS THAT WERE BOTH EFFECTIVE AND POLITICALLY BY THE MIDDLE OF THE CENTURY THE FORCES OF STATE REPRESSION COUPLED WITH THE LONGEVITY OF THE PROBLEM HAD ALREADY CREATED SUCH AN INTOLERABLE SITUATION THAT FIXING THE SYSTEM THROUGH REFORM WAS ESSENTIALLY THE ONLY REASONABLE ANSWER TO THIS KIND OF SITUATION IS THE ONLY WAY TO LIVE IS TO RUSSIA HAD BECOME A STIFLING BACKWARDS COUNTRY RUN BY A RULING ELITE GROWN FABULOUSLY WEALTHY THROUGH RAMPANT NATURAL RESOURCE THE RUSSIAN GOVERNMENT HAD BECOME COMPLETELY DISCONNECTED FROM ITS SUBJECTS AND NEW INFORMATION AND NEW IDEAS WERE IMPOSSIBLE TO PREVENT FROM SEEPING INTO THE COUNTRY FROM THE HEATED AND BUBBLING SOCIAL SCENE IN WESTERN EVEN A BRUTAL AND VIOLENT COULD NOT STOP THE NIHILISTS OTHER DEDICATED REVOLUTIONARIES OR THE INEVITABLE OUTCOME OF THE JEWEL ENCRUSTED FABERGE EGGS WERE AN EMBLEMATIC EXPRESSION OF LATE CENTURY IMPERIAL RUSSIAN WEALTH AND A GROSSLY DISTORTED SOCIETY WHERE THE MONARCHY COULD COMMISSION DOZENS OF THESE EGGS WHILE THE GENERAL PUBLIC WORKED AND STARVED TO THE HEART OF RUSSIAN NIHILISM WAS ABOUT BREAKING WITH THE FAILURES OF THE PAST AND ABOUT CRAFTING A NEW THIS WAS THE MEANING OF THE FATHERS AND SONS PHRASE USED AT THE TIME AND REMEMBERED TODAY IN TURGENEVS NOVEL OF THE SAME WHEREAS THE FATHERS GREW UP ON GERMAN IDEALISTIC PHILOSOPHY AND ROMANTICISM IN GENERAL WITH ITS EMPHASIS ON THE METAPHYSICAL RELIGIOUS AESTHETIC AND HISTORICAL APPROACHES TO REALITY THE SONS LED BY SUCH YOUNG RADICALS AS NICHOLAS CHERNYSHEVSKY NICHOLAS DOBROLIUBOV AND DMITRII PISAREV HOISTED THE BANNER OF UTILITARIANISM POSITIVISM MATERIALISM AND ESPECIALLY NIHILISM AND ALSO IN LARGE PART REALISM PARTICULARLY CRITICAL REALISM MEANT ABOVE ALL ELSE A FUNDAMENTAL REBELLION AGAINST ACCEPTED VALUES AND AGAINST ABSTRACT THOUGHT AND FAMILY CONTROL AGAINST LYRIC POETRY AND SCHOOL DISCIPLINE AGAINST RELIGION AND THE EARNEST YOUNG MEN AND WOMEN OF THE WANTED TO CUT THROUGH EVERY POLITE VENEER TO GET RID OF ALL CONVENTIONAL SHAM TO GET TO THE BOTTOM OF WHAT THEY USUALLY CONSIDERED REAL AND WORTHWHILE INCLUDED THE NATURAL AND PHYSICAL SCIENCES FOR THAT WAS THE AGE WHEN SCIENCE CAME TO BE GREATLY ADMIRED IN THE WESTERN WORLD SIMPLE AND SINCERE HUMAN RELATIONS AND A SOCIETY BASED ON KNOWLEDGE AND REASON RATHER THAN IGNORANCE PREJUDICE EXPLOITATION AND THIS WAS ABOUT THE DESTRUCTION OF IDOLS ABOUT BURNING THE DEAD WOOD OF AND THE RUSSIAN NIHILISTS WERE QUITE REVOLUTIONARY ESPECIALLY GIVEN THE CONTEXT OF THE TIME AND LOCATION THEY EXISTED IN FOR THEY INCLUDE SECTIONS OF THE POPULATION THAT HAD LITTLE IF ANY REPRESENTATION WOMEN FOR EXAMPLE PLAYED A KEY ROLE AND INCLUDED SOME OF THE MOST MOTIVATED AND CHARISMATIC CHARACTERS OF THE TIME PERIOD LIKE VERA FIGNER AND SOPHIA THE FEMINISTS WANTED TO CHANGE PIECES OF THE WORLD THE NIHILISTS WANTED TO CHANGE THE WORLD ITSELF THOUGH NOT NECESSARILY THROUGH POLITICAL THE RUSSIAN WORD FOR A FEMALE NIHILIST IS ITS IMPORTANT TO POINT OUT THAT THE NIHILIST ETHOS OF THE TIME WAS PRIMARILY INDIVIDUALISTIC AND NOT ALWAYS POLITICALLY SOME RADICAL NIHILIST ATTITUDES PRECLUDED IDEOLOGICAL OR POLITICAL NIHILISM EMANCIPATED THE YOUNG RUSSIAN RADICALS FROM ANY ALLEGIANCE TO THE ESTABLISHED ORDER IT WAS TO REPEAT A POINT INDIVIDUAL RATHER THAN SOCIAL BY ITS VERY NATURE AND LACKED A POSITIVE PROGRAM BOTH PISAREV AND TURGENEVS HERO BAZAROV DIED CLOTHING ATTITUDE COMMUNICATIONS STYLE ALL WERE PORTIONS OF THE NEW NIHILIST THE CLOTHING STYLE SOUGHT FUNCTIONALITY AND USEFULNESS OVER FRIVOLOUS THE REVOLT IN THE DRESS OF THE NIGILISTKA WENT SOMETHING LIKE ONE OF THE MOST INTERESTING AND WIDELY REMARKED FEATURES OF THE NIGILISTKA WAS HER PERSONAL DISCARDING THE MUSLIN RIBBONS FEATHERS PARASOLS AND FLOWERS OF THE RUSSIAN LADY THE ARCHETYPICAL GIRL OF THE NIHILIST PERSUASION IN THE WORE A PLAIN DARK WOOLEN DRESS WHICH FELL STRAIGHT AND LOOSE FROM THE WAIST WITH WHITE CUFFS AND COLLAR AS THE ONLY THE HAIR WAS CUT SHORT AND WORN STRAIGHT AND THE WEARER FREQUENTLY ASSUMED DARK NIGILISTKA FASHION WAS ABOUT MORE THAN JUST JUVENILE REBELLION AGAINST BOURGEOISIE FASHION BECAUSE INSTEAD OF SIMPLY CONTRADICTING ESTABLISHED FORMS IT WENT ON TO CREATE ITS OWN WAS THE REASON BEHIND MUCH OF MACHINERY OF SEXUAL ATTRACTION THROUGH OUTWARD APPEARANCE THAT LED INTO SLAVERY WAS DISCARDED BY THE NEW WOMAN WHOSE NIHILIST CREED TAUGHT HER THAT SHE MUST MAKE HER WAY WITH KNOWLEDGE AND ACTION RATHER THAN FEMININE EVEN DEEPER THAN CHANGES IN SUPERFICIAL APPEARANCE EXISTED A NEW AND QUITE PROFOUND REALIZATION FOR THE NIGILISTKA UNDERSTOOD THAT LIFE HAD TO BE DEFINED INTERNALLY AND NOT SOLELY BY EXTERNAL AUTHORITIES OR TO ESTABLISH HER IDENTITY SHE NEEDED A CAUSE OR A PATH RATHER THAN JUST A AN INTERESTING DEPARTURE ALSO OCCURRED IN COMMUNICATIONS TYPICAL NIGILISTKA LIKE HER MALE COMRADE REJECTED THE CONVENTIONAL HYPOCRISY OF INTERPERSONAL RELATIONS AND TENDED TO BE DIRECT TO THE POINT OF SEVERE TIMES CALL FOR SEVERE SEEING THEIR EFFORTS AT SOCIAL CHANGE ONLY BEING MET WITH POLICE BRUTALITY AND INCREASING REPRESSION BY DESPOTIC AUTHORITY THE REVOLUTIONARIES REASSESSED THEIR PETER TKACHEV AND SERGEI NECHAYEV WERE TWO THAT FELT SEVERE TIMES CALL FOR SEVERE MEASURES THE REVOLUTION WAS ONLY GETTING SEVERAL YEARS OF REVOLUTIONARY CONSPIRACY TERRORISM AND ASSASSINATION THE FIRST INSTANCES OF VIOLENCE OCCURRED MORE OR LESS SPONTANEOUSLY SOMETIMES AS COUNTERMEASURES AGAINST BRUTAL POLICE THUS EARLY IN VERA ZASULICH SHOT AND WOUNDED THE MILITARY GOVERNOR OF PETERSBURG GENERAL THEODORE TREPOV WHO HAD ORDERED A POLITICAL PRISONER TO BE A JURY FAILED TO CONVICT HER WITH THE RESULT THAT POLITICAL CASES WERE WITHDRAWN FROM REGULAR JUDICIAL BUT BEFORE LONG AN ORGANIZATION EMERGED WHICH CONSCIOUSLY PUT TERRORISM AT THE CENTER OF ITS THE CONSPIRATORIAL REVOLUTIONARY SOCIETY LAND AND FREEDOM FOUNDED IN SPLIT IN INTO TWO THE BLACK PARTITION OR TOTAL LAND REPARTITION WHICH EMPHASIZED GRADUALISM AND PROPAGANDA AND THE WILL OF THE PEOPLE WHICH MOUNTED AN TERRORISTIC OFFENSIVE AGAINST THE MEMBERS OF THE WILL OF THE PEOPLE BELIEVED THAT BECAUSE OF THE HIGHLY CENTRALIZED NATURE OF THE RUSSIAN STATE A FEW ASSASSINATIONS COULD DO TREMENDOUS DAMAGE TO THE REGIME AS WELL AS PROVIDE THE REQUISITE POLITICAL INSTRUCTION FOR THE EDUCATED SOCIETY AND THE THEY SELECTED THE EMPEROR ALEXANDER II AS THEIR CHIEF TARGET AND CONDEMNED HIM TO WHAT FOLLOWED HAS BEEN DESCRIBED AS AN EMPEROR HUNT AND IN CERTAIN WAYS IT DEFIES THE EXECUTIVE COMMITTEE OF THE WILL OF THE PEOPLE INCLUDED ONLY ABOUT THIRTY MEN AND WOMEN LED BY SUCH PERSONS AS ANDREW ZHELIABOV WHO CAME FROM THE SERFS AND SOPHIA PEROVSKAIA WHO CAME FROM RUSSIAS HIGHEST ADMINISTRATIVE CLASS BUT IT FOUGHT THE RUSSIAN AFTER THE ASSASSINATION OF THE TSAR SOME BEGAN TO QUESTION THE STRATEGIC USEFULNESS OF THE SPIRALING VIOLENCE BUT FEW ALTERNATIVES EXISTED IN THE OPPRESSIVE MILIEU OF IMPERIAL SUBSEQUENT MONARCHS ALEXANDER III AND NICHOLAS II ONLY BECAME MORE REACTIONARY AND WHILE SIMULTANEOUSLY VOIDING EVEN MINIMAL PUBLIC MURDER AND THE GIBBET CAPTIVATED THE IMAGINATION OF OUR YOUNG AND THE WEAKER THEIR NERVES AND THE MORE OPPRESSIVE THEIR SURROUNDINGS THE GREATER WAS THEIR SENSE OF EXALTATION AT THE THOUGHT OF REVOLUTIONARY VERA FIGNER";

var IGNORES = ['', ' ', '\n'];

var Corpus = function(corpus) {
  var _learn = function(state, next_word) {
    var memory = state.memory,
        prev_word = state.prev_word;

    if (next_word in IGNORES) {
      return state;
    }

    if (!memory[prev_word]) {
      memory[prev_word] = [];
    }

    memory[prev_word].push(next_word);

    return {memory: memory, prev_word: next_word};
  };

  corpus = corpus || [FASHION, NIHILISM].join(' ');
  var words = corpus.split(' ');
  this.memory = words.reduce(_learn, {memory: {}, prev_word: ''}).memory;
}

Corpus.prototype.suggest = function() {
  var options = Object.keys(this.memory);
  return options[Math.floor(Math.random() * options.length)];
};

Corpus.prototype.next = function(from) {
  var options = this.memory[from];

  if (!options || !options.length) {
    return this.suggest();
  }

  return options[Math.floor(Math.random() * options.length)];
};

Corpus.prototype.sentence = function() {
  var word = this.suggest();
  var sentence = [];
  var size = Math.round(Math.random() * (5 - 2) + 2);
  for (var x = 0; x < size; x++) {
    word = this.next(word);
    sentence.push(word);
  }

  return sentence.join(' ');
}
