var FASHION = "" +
"WHOS WEARING WHAT AND WHERE THIS WEEK SEE WHO ROCKED IT ON THE RED CARPET AND " +
"WHOSE STREET STYLE WERE CRUSHING IN OUR WEEKLY EDIT OF BEST DRESSED STARS " +
"YESTERDAY BURBERRY HOSTED ONE OF THE MOST STARSTUDDED CATWALK SHOWS WEVE SEEN " +
"IN A LONG TIME HELD IN LA THE EVENT SAW MOST OF LONDON AND HOLLYWOOD COMBINE TO " +
"WATCH THE ACTION CLOTHES WERE MODELLED BY THE BRIT PACK MOST NOTABLY THE LEGEND " +
"NAOMI CAMPBELL AND THE BECKHAMS CARA DELEVINGNE ANNA WINTOUR AND ROSIE " +
"HUNTINGTONWHITELY WERE SAT FROM ROW TO SUPPORT CREATIVE DIRECTOR CHRISTOPHER " +
"BAILEY WHAT MADE YOU WANT TO DO A SHOE LINE NOW I HAVE ALWAYS BEEN ATTRACTED TO " +
"FASHION THAT IS TRANSITIONAL WEAR MEANING DESIGNS THAT CARRY A WOMAN FROM " +
"SEASON TO SEASON FROM DAY TO NIGHT THAT WAS A SIGNIFICANT PART OF THE THOUGHT " +
"PROCESS FOR THIS COLLECTION I WANTED TO THINK ABOUT FOOTWEAR THAT IS " +
"DIRECTIONAL AND ALSO COMFORTABLE I LIKE MY SHOES TO HAVE A BIT OF PERSONALITY " +
"WHY WAS MATISSE A GOOD PARTNER FOR YOU WE WERE INTRODUCED BY A MUTUAL FRIEND " +
"AND FELT WE WOULD WORK WELL TOGETHER ALL COLLABORATIONS I HAVE BEEN INVOLVED " +
"WITH STARTED ORGANICALLY THERE MUST BE A COMMON GOAL IN MIND TO UNDERSTAND AND " +
"APPRECIATE THE PERSON WE ARE DESIGNING FOR MATISSE IS SUCCESSFUL AT " +
"UNDERSTANDING THEIR CUSTOMER BUT WAS ALSO LOOKING FOR SOMEONE TO BRING A " +
"DIFFERENT PERSPECTIVE AT A SLIGHTLY HIGHER PRICE POINT I FELT I COULD HELP THEM " +
"ACHIEVE THIS VISION WHAT WAS THE INSPIRATION FOR THE COLLECTION I FIND " +
"INSPIRATION IN MANY THINGS FROM ART TO FILM TO WHAT IS RELEVANT IN FASHION " +
"CURRENTLY OR WHAT I WOULD LIKE TO SEE COME BACK AROUND AND FROM MY OWN LIFE " +
"EXPERIENCES ONE OF MY FAVORITE ARTISTS IS ED RUSCHA HIS HOT SHOT PIECE BECAME " +
"MY MAIN INSPIRATION FOR THE HOYT THE DAWN STYLE IS SLIGHTLY SURF INSPIRED WE " +
"UTILIZED NEOPRENE AND IS A NOD TO MY BLUE CRUSH DAYS ARE THERE ANY GIRLS WHO " +
"INSPIRE YOU LOTS OF THEM I LOVE SEEING GIRLS WHO FEEL CONFIDENT WITH THEMSELVES " +
"AND EMBRACE THEIR INDIVIDUALITY MY STEPDAUGHTER JASPER IS ONE WHATS YOUR DESIGN " +
"PROCESS LIKE INITIALLY I BROUGHT IN A VARIETY OF IMAGES TO DICTATE THE MOOD FOR " +
"AN OVERALL SCOPE OF THE COLLECTION THOUGH THERE ARE ONLY ABOUT  STYLES IN THIS " +
"COLLABORATION I KNEW I WANTED IT TO FEEL DIVERSE MY OWN STYLE CAN VARY FROM " +
"BOHEMIAN TO SPORTY TO MINIMALIST I WANTED TO TRANSLATE THIS KALEIDOSCOPIC FEEL " +
"INTO THE COLLECTION IN THIS SENSE THERE IS SOMETHING THAT CAN APPEAL TO MANY " +
"DIFFERENT WOMEN MOODS AND STYLE OF DRESS ONCE WE KNEW THE SHAPES OF THE SHOES " +
"WE DECIDED ON MATERIAL METALS AND EMBELLISHMENTS ONCE THESE DECISIONS ARE MADE " +
"AND THE DESIGNS ARE LOCKED THE SAMPLING PROCESS BEGINS AND AMENDMENTS ARE MADE " +
"WHEN NECESSARY HOW WILL YOU PERSONALLY STYLE THEM I WANTED TO CREATE SHAPES " +
"THAT ARE VERSATILE AND CAN BE WORN IN MANY WAYS I CAN WEAR THE KELLY STRAPPY " +
"SANDAL WITH DENIM SILK SHORTS OR A LITTLE SUMMER DRESS THE BOOTIES CAN BE WORN " +
"IN A MORE FOLKINSPIRED MANNER PAIRED WITH A LONG SKIRT ID LOVE TO SEE THE DAWN " +
"SPORTY SANDAL WORKS WITH A LONG BLACK SLIP DRESSTO BALANCE THE FEMININITY OF " +
"THE DRESS WITH A SPORTIER SHOE KARL LAGERFELD IS THE LATEST TO ACCESSORIZE WITH " +
"THE NEW APPLE WATCHONLY HIS IS CUSTOMMADE OF COURSE THE KAISER STYLED THE SOLID " +
"GOLD LINK WATCH WITH HIS SIGNATURE GLOVES NATURALLY IN AN INSTAGRAM SNAPPED BY " +
"ASSISTANT SEBASTIEN JONDEAU IF YOU HAD ANY DOUBTS ABOUT THE NEW WEARABLE TECH " +
"BEFORE THIS DEFINITELY CEMENTS ITS FASHION STATUS WITH ONLY TWO WEEKS UNTIL THE " +
"HIGHLY COVETED APPLE WATCH MAKES ITS OFFICIAL DEBUT THE NEW WEARABLE TECH IS " +
"ALREADY POPPING UP ON THE WRISTS OF CELEBRITIES CHRISTIE TURLINGTONBURNS " +
"SPORTED HER NEW WRIST CANDY WHILE PREPPING FOR THE LONDON MARATHON WHILE KATY " +
"PERRY SHARED A SNAP OF HER PLAYFUL NEW MICKEY MOUSE STYLE WATCHACTING AS THE " +
"FIRST REALLIFE MODELS OF THE NEW APPLE TECH PIECE THE SUPERMODEL OFFICIALLY " +
"RETIRES FROM THE CATWALK AFTER YEARS AND AN ABSOLUTELY LEGENDARY CAREER GISELE " +
"BNDCHEN IS SAYING FAREWELL TO THE CATWALK FOREVER GISELE IS CONSIDERED ONE OF " +
"THE MOST SUCCESSFUL AND CELEBRATED SUPERMODELS OF ALL TIME FORBES ESTIMATED HER " +
"EARNINGS AT MILLION WHICH INCLUDES INCOME FROM MODELING CONTRACTS AND NUMEROUS " +
"ENDORSEMENT DEALS RUMORS OF GISELES RETIREMENT HAVE BEEN FLOATING FOR QUITE " +
"SOME TIME NOW BUT ON WEDNESDAY SHE PERSONALLY CONFIRMED THE NEWS TO HER FANS ON " +
"INSTAGRAM SHE ANNOUNCED THAT WEDNESDAY EVENING HER APPEARANCE AT THE COLCCI " +
"SHOW DURING SAO PAULO FASHION WEEK WOULD BE HER LAST EVER FASHION SHOW I AM " +
"GRATEFUL THAT AT I WAS GIVEN THE OPPORTUNITY TO START THIS JOURNEY WROTE GISELE " +
"WHO IS MARRIED TO NFL STAR TOM BRADY AND HAS TWO CHILDREN BENJAMIN  AND VIVIAN " +
"TODAY AFTER YEARS IN THE INDUSTRY IT IS A PRIVILEGE TO BE DOING MY LAST " +
"FASHION SHOW BY CHOICE AND YET STILL BE WORKING IN OTHER FACETS OF THE BUSINESS " +
"IN AN INTERVIEW WITH FOLHA DE SAO PAULO VIA YAHOO GISELE SAID HER BODY TOLD HER " +
"IT WAS TIME TO STOP AUTOMATICALLY MY BODY TELLS ME IF WHAT I DO IS WORTH IT AND " +
"IT ASKED TO STOP I RESPECT MY BODY ITS A PRIVILEGE TO BE ABLE TO STOP RUNWAY " +
"WORK SHE SAID FANS CAN LOOK FORWARD TO THE FACT THAT GISELE ISNT WALKING WAY " +
"FROM FASHION ALTOGETHER SHES JUST LEAVING THE RUNWAY TO FOCUS ON MORE PROJECTS " +
"SHE HAS PLANNED FOR THE FUTURE I DONT SEE HOW TO CONTINUE RUNWAY MODELING " +
"GISELE SAID STOPPING WILL LEAVE ROOM FOR OTHER PROJECTS I HAVE FOR MYSELF ON " +
"HER LAST DAY ON THE CATWALK HER SPIRITS SEEMED HIGH SHE EVEN POSTED A " +
"BEHINDTHESCENES PIC FOR FANS AS SHE TOOK HER LAST FEW STRUTS HER FELLOW RUNWAY " +
"MODELS APPLAUDED HER AND WITH THAT GISELE SAID GOODBYE TO RUNWAY MODELING " +
"";

var NIHILISM = "";

var IGNORES = ['', ' ', '\n'];

var Corpus = function(corpus) {
  var _learn = function(state, next_word) {
    var memory = state.memory,
        prev_word = state.prev_word;

    if (next_word in IGNORES) {
      return state;
    }

    if (!memory[prev_word]) {
      memory[prev_word] = [];
    }

    memory[prev_word].push(next_word);

    return {memory: memory, prev_word: next_word};
  };

  corpus = corpus || [FASHION, NIHILISM].join(' ');
  var words = corpus.split(' ');
  this.memory = words.reduce(_learn, {memory: {}, prev_word: ''}).memory;
}

Corpus.prototype.suggest = function() {
  var options = Object.keys(this.memory);
  return options[Math.floor(Math.random() * options.length)];
};

Corpus.prototype.next = function(from) {
  var options = this.memory[from];

  if (!options || !options.length) {
    return this.suggest();
  }

  return options[Math.floor(Math.random() * options.length)];
};

Corpus.prototype.sentence = function() {
  var word = this.suggest();
  var sentence = [];
  var size = Math.round(Math.random() * (5 - 2) + 2);
  for (var x = 0; x < size; x++) {
    word = this.next(word);
    sentence.push(word);
  }

  return sentence.join(' ');
}
