var FASHION = "" +
"WHOS WEARING WHAT AND WHERE THIS WEEK SEE WHO ROCKED IT ON THE RED CARPET AND " +
"WHOSE STREET STYLE WERE CRUSHING IN OUR WEEKLY EDIT OF BEST DRESSED STARS " +
"YESTERDAY BURBERRY HOSTED ONE OF THE MOST STARSTUDDED CATWALK SHOWS WEVE SEEN " +
"IN A LONG TIME HELD IN LA THE EVENT SAW MOST OF LONDON AND HOLLYWOOD COMBINE TO " +
"WATCH THE ACTION CLOTHES WERE MODELLED BY THE BRIT PACK MOST NOTABLY THE LEGEND " +
"NAOMI CAMPBELL AND THE BECKHAMS CARA DELEVINGNE ANNA WINTOUR AND ROSIE " +
"HUNTINGTONWHITELY WERE SAT FROM ROW TO SUPPORT CREATIVE DIRECTOR CHRISTOPHER " +
"BAILEY WHAT MADE YOU WANT TO DO A SHOE LINE NOW I HAVE ALWAYS BEEN ATTRACTED TO " +
"FASHION THAT IS TRANSITIONAL WEAR MEANING DESIGNS THAT CARRY A WOMAN FROM " +
"SEASON TO SEASON FROM DAY TO NIGHT THAT WAS A SIGNIFICANT PART OF THE THOUGHT " +
"PROCESS FOR THIS COLLECTION I WANTED TO THINK ABOUT FOOTWEAR THAT IS " +
"DIRECTIONAL AND ALSO COMFORTABLE I LIKE MY SHOES TO HAVE A BIT OF PERSONALITY " +
"WHY WAS MATISSE A GOOD PARTNER FOR YOU WE WERE INTRODUCED BY A MUTUAL FRIEND " +
"AND FELT WE WOULD WORK WELL TOGETHER ALL COLLABORATIONS I HAVE BEEN INVOLVED " +
"WITH STARTED ORGANICALLY THERE MUST BE A COMMON GOAL IN MIND TO UNDERSTAND AND " +
"APPRECIATE THE PERSON WE ARE DESIGNING FOR MATISSE IS SUCCESSFUL AT " +
"UNDERSTANDING THEIR CUSTOMER BUT WAS ALSO LOOKING FOR SOMEONE TO BRING A " +
"DIFFERENT PERSPECTIVE AT A SLIGHTLY HIGHER PRICE POINT I FELT I COULD HELP THEM " +
"ACHIEVE THIS VISION WHAT WAS THE INSPIRATION FOR THE COLLECTION I FIND " +
"INSPIRATION IN MANY THINGS FROM ART TO FILM TO WHAT IS RELEVANT IN FASHION " +
"CURRENTLY OR WHAT I WOULD LIKE TO SEE COME BACK AROUND AND FROM MY OWN LIFE " +
"EXPERIENCES ONE OF MY FAVORITE ARTISTS IS ED RUSCHA HIS HOT SHOT PIECE BECAME " +
"MY MAIN INSPIRATION FOR THE HOYT THE DAWN STYLE IS SLIGHTLY SURF INSPIRED WE " +
"UTILIZED NEOPRENE AND IS A NOD TO MY BLUE CRUSH DAYS ARE THERE ANY GIRLS WHO " +
"INSPIRE YOU LOTS OF THEM I LOVE SEEING GIRLS WHO FEEL CONFIDENT WITH THEMSELVES " +
"AND EMBRACE THEIR INDIVIDUALITY MY STEPDAUGHTER JASPER IS ONE WHATS YOUR DESIGN " +
"PROCESS LIKE INITIALLY I BROUGHT IN A VARIETY OF IMAGES TO DICTATE THE MOOD FOR " +
"AN OVERALL SCOPE OF THE COLLECTION THOUGH THERE ARE ONLY ABOUT  STYLES IN THIS " +
"COLLABORATION I KNEW I WANTED IT TO FEEL DIVERSE MY OWN STYLE CAN VARY FROM " +
"BOHEMIAN TO SPORTY TO MINIMALIST I WANTED TO TRANSLATE THIS KALEIDOSCOPIC FEEL " +
"INTO THE COLLECTION IN THIS SENSE THERE IS SOMETHING THAT CAN APPEAL TO MANY " +
"DIFFERENT WOMEN MOODS AND STYLE OF DRESS ONCE WE KNEW THE SHAPES OF THE SHOES " +
"WE DECIDED ON MATERIAL METALS AND EMBELLISHMENTS ONCE THESE DECISIONS ARE MADE " +
"AND THE DESIGNS ARE LOCKED THE SAMPLING PROCESS BEGINS AND AMENDMENTS ARE MADE " +
"WHEN NECESSARY HOW WILL YOU PERSONALLY STYLE THEM I WANTED TO CREATE SHAPES " +
"THAT ARE VERSATILE AND CAN BE WORN IN MANY WAYS I CAN WEAR THE KELLY STRAPPY " +
"SANDAL WITH DENIM SILK SHORTS OR A LITTLE SUMMER DRESS THE BOOTIES CAN BE WORN " +
"IN A MORE FOLKINSPIRED MANNER PAIRED WITH A LONG SKIRT ID LOVE TO SEE THE DAWN " +
"SPORTY SANDAL WORKS WITH A LONG BLACK SLIP DRESSTO BALANCE THE FEMININITY OF " +
"THE DRESS WITH A SPORTIER SHOE KARL LAGERFELD IS THE LATEST TO ACCESSORIZE WITH " +
"THE NEW APPLE WATCHONLY HIS IS CUSTOMMADE OF COURSE THE KAISER STYLED THE SOLID " +
"GOLD LINK WATCH WITH HIS SIGNATURE GLOVES NATURALLY IN AN INSTAGRAM SNAPPED BY " +
"ASSISTANT SEBASTIEN JONDEAU IF YOU HAD ANY DOUBTS ABOUT THE NEW WEARABLE TECH " +
"BEFORE THIS DEFINITELY CEMENTS ITS FASHION STATUS WITH ONLY TWO WEEKS UNTIL THE " +
"HIGHLY COVETED APPLE WATCH MAKES ITS OFFICIAL DEBUT THE NEW WEARABLE TECH IS " +
"ALREADY POPPING UP ON THE WRISTS OF CELEBRITIES CHRISTIE TURLINGTONBURNS " +
"SPORTED HER NEW WRIST CANDY WHILE PREPPING FOR THE LONDON MARATHON WHILE KATY " +
"PERRY SHARED A SNAP OF HER PLAYFUL NEW MICKEY MOUSE STYLE WATCHACTING AS THE " +
"FIRST REALLIFE MODELS OF THE NEW APPLE TECH PIECE THE SUPERMODEL OFFICIALLY " +
"RETIRES FROM THE CATWALK AFTER YEARS AND AN ABSOLUTELY LEGENDARY CAREER GISELE " +
"BNDCHEN IS SAYING FAREWELL TO THE CATWALK FOREVER GISELE IS CONSIDERED ONE OF " +
"THE MOST SUCCESSFUL AND CELEBRATED SUPERMODELS OF ALL TIME FORBES ESTIMATED HER " +
"EARNINGS AT MILLION WHICH INCLUDES INCOME FROM MODELING CONTRACTS AND NUMEROUS " +
"ENDORSEMENT DEALS RUMORS OF GISELES RETIREMENT HAVE BEEN FLOATING FOR QUITE " +
"SOME TIME NOW BUT ON WEDNESDAY SHE PERSONALLY CONFIRMED THE NEWS TO HER FANS ON " +
"INSTAGRAM SHE ANNOUNCED THAT WEDNESDAY EVENING HER APPEARANCE AT THE COLCCI " +
"SHOW DURING SAO PAULO FASHION WEEK WOULD BE HER LAST EVER FASHION SHOW I AM " +
"GRATEFUL THAT AT I WAS GIVEN THE OPPORTUNITY TO START THIS JOURNEY WROTE GISELE " +
"WHO IS MARRIED TO NFL STAR TOM BRADY AND HAS TWO CHILDREN BENJAMIN  AND VIVIAN " +
"TODAY AFTER YEARS IN THE INDUSTRY IT IS A PRIVILEGE TO BE DOING MY LAST " +
"FASHION SHOW BY CHOICE AND YET STILL BE WORKING IN OTHER FACETS OF THE BUSINESS " +
"IN AN INTERVIEW WITH FOLHA DE SAO PAULO VIA YAHOO GISELE SAID HER BODY TOLD HER " +
"IT WAS TIME TO STOP AUTOMATICALLY MY BODY TELLS ME IF WHAT I DO IS WORTH IT AND " +
"IT ASKED TO STOP I RESPECT MY BODY ITS A PRIVILEGE TO BE ABLE TO STOP RUNWAY " +
"WORK SHE SAID FANS CAN LOOK FORWARD TO THE FACT THAT GISELE ISNT WALKING WAY " +
"FROM FASHION ALTOGETHER SHES JUST LEAVING THE RUNWAY TO FOCUS ON MORE PROJECTS " +
"SHE HAS PLANNED FOR THE FUTURE I DONT SEE HOW TO CONTINUE RUNWAY MODELING " +
"GISELE SAID STOPPING WILL LEAVE ROOM FOR OTHER PROJECTS I HAVE FOR MYSELF ON " +
"HER LAST DAY ON THE CATWALK HER SPIRITS SEEMED HIGH SHE EVEN POSTED A " +
"BEHINDTHESCENES PIC FOR FANS AS SHE TOOK HER LAST FEW STRUTS HER FELLOW RUNWAY " +
"MODELS APPLAUDED HER AND WITH THAT GISELE SAID GOODBYE TO RUNWAY MODELING " +
"I AM A WOMAN HAPPILY MARRIED FOR THE LAST TWO YEARS LIVING IN A GREAT HOME IVE " +
"BEEN ACTIVELY BUILDING THE LIFE IVE ALWAYS DREAMED OF BUT I HAVE A STEADY " +
"CORPORATE JOB AT A BANK WHICH I FEEL ABSOLUTELY NOTHING FOR WHATS WORSE MY " +
"  MANAGER RETIRED AND I HATE MY NEW BOSS SO MY EASY SECURE JOB IS NOW THE " +
"SEVENTH CIRCLE OF HELL EVERY DAY I DREAD WALKING INTO MY BUILDING AND FEEL LIKE " +
"A TOTAL FAILURE WHO IS WASTING AWAY HER LIFE WITH EVERY PASSING HEARTBEAT  NOW " +
"I ONLY WANT TO START A FAMILY BUT I FEEL THAT IF I DO I WILL NEVER GO BACK TO " +
"  WORK NOR WILL I FIGURE OUT WHAT I WANT TO DO WITH MYSELF CAREERWISE IM " +
"LOOKING FOR A NEW JOB AT THE SAME COMPANY BUT MY HEART ISNT IN IT BECAUSE IM " +
"  NOT INTERESTED IN THE INDUSTRY AND ID STILL BE AN ANONYMOUS AND INVISIBLE " +
"EMPLOYEE OF AN ENORMOUS CORPORATION BUT IM AFRAID OF LEAVING BECAUSE THIS JOB " +
"HAS GREAT BENEFITS ESPECIALLY WHEN IT COMES TO MATERNITY LEAVE I WOULD LEAVE " +
"FOR A DREAM JOB BUT I HAVE NO IDEA WHAT THAT IS MY REAL DREAM IS TO BE THE " +
"  PARENT WHO WORKS FROM HOME OR FOR HERSELF  AS FAR AS CAREERS GO I CAN SEE " +
"    MYSELF AS AN INTERIOR DESIGNER OR IN THE HOSPITALITY INDUSTRY OR MAYBE AS " +
"SOME KIND OF BROADCAST JOURNALIST I AM CREATIVE AND I LOVE TO WRITE I OFTEN " +
"CONSIDER GOING BACK TO SCHOOL FOR BROADCAST JOURNALISM A FOURYEAR PROGRAM BUT I " +
"  WILL SURELY BE PREGNANT BYBEFORE GRADUATION AND THEN WHAT THE DEGREE GOES ON " +
"HOLD WHILE I BUILD MY FAMILY I READ A LOT ABOUT WOMEN AND CAREERS AND FEEL THAT " +
"  BY NOW I SHOULD HAVE A JOB I CAN LEAN IN TO SO THAT WHEN I BOW OUT AND BECOME " +
"A PARENT I HAVE A GOOD CAREER FOUNDATION ESTABLISHED I ALSO FEEL THAT IF I WANT " +
"  TO HAVE ANY SEMBLANCE OF A CAREER WHILE JUGGLING FAMILY I SHOULD PROBABLY BE " +
"    PREGNANT YESTERDAY SO THAT ILL ONLY BE IN MY S WHEN MY KIDS ARE  I HAVE " +
"CONSIDERED STARTING A SMALL BUSINESS I COULD HANDLE PARTTIME BUT I CANT INVEST " +
"THE TIME SINCE I ONLY HAVE EVENINGS AND WEEKENDS TO GET ANYTHING DONE  I FEEL " +
"PLAGUED BY ALL THE THINGS I SHOULD BE DOING WITH MY CAREER LIFE BEFORE GETTING " +
"PREGNANT SHOULD I MOVE ON TO A DIFFERENT LESSSHITTY CORPORATE JOB THEN GET " +
"PREGNANT SHOULD I TAKE THE TIME TO REALLY FIGURE OUT WHAT I WANT TO DO FOR WORK " +
"  THEN PURSUE IT FULLY SHOULD I QUIT MY JOB TO SET UP A SMALL SIDEBUSINESS " +
"BEFORE IM PREGNANT OR INVEST IN THIS VENTURE ONLY ON EVENINGS AND WEEKENDS " +
"SHOULD I JUST GET PREGNANT SOONISH ROLL THE DICE SEE WHERE THE CAREER CHIPS " +
"FALL  MY HUSBAND WORKS FOR SMALL COMPANIES AND WE RELY ON MY JOB FOR THE " +
"  BANKING PERKS AND JOB SECURITY BUT HES SUPPORTIVE OF ANYTHING I WISH TO DO HE " +
"JUST WANTS ME TO DECIDE AND TO COMMIT I HAVE NO IDEA WHAT TO DECIDE AND I AM SO " +
"SCARED OF COMMITTING I HAVE ASKED THIS SAME QUESTION TO MY FRIENDS PEERS ELDERS " +
"AND FAMILY EVERYONES ANSWERS VARY  DONT GET PREGNANT WHILE YOU HATE YOUR JOB " +
"  YOULL BE SO HORMONAL AND EMOTIONAL AND PREGNANCY IS SUPPOSED TO BE A HAPPY " +
"TIME  GET PREGNANT WHILE YOURE AT THIS JOB AND MILK IT FOR ALL ITS WORTH  QUIT " +
"  YOUR JOB ALTOGETHER AND FIND OUT WHAT YOU WANT TO DO  NO ONE UNDERSTANDS THE " +
"VARIABLES  THAT WE CANNOT AFFORD TO LOSE MY JOB THAT I NEED TO WORK HERE UNTIL " +
"I HAVE SOMETHING NEW THAT I DONT ACTUALLY GIVE A FUCK ABOUT FINDING SOMETHING " +
"NEW BECAUSE I DONT WANT TO WORK I WANT TO BE AT HOME WITH BABIES I FEEL LIKE " +
"ITS A CRIME TO SAY THIS OUT LOUD I FEEL JUDGED AND JUDGE MYSELF HARSHLY WHEN I " +
"SAY THIS I AM A SMART AND CAPABLE WOMAN WHO SHOULD HAVE A MEANINGFUL CAREER AND " +
"IF I DONT IM NOT A SMART CAPABLE WOMAN IM JUST A PARENT I FEEL SO MUCH PRESSURE " +
"  TO BE THE CAREER WOMAN WHO HAS IT ALL I WORRY THAT BY HAVING A FAMILY ILL " +
"NEVER HAVE A CAREER AND I FEEL PLAGUED BY THE FACT THAT I DONT HONESTLY CARE " +
"ENOUGH ABOUT BUILDING A CAREER BECAUSE ALL I WANT IS TO MAKE A BEAUTIFUL HOME " +
"AND RAISE A BEAUTIFUL FAMILY WITH MY BEAUTIFUL HUSBAND BUT THEN IN TEN YEARS " +
"MAYBE I WILL REGRET NOT HAVING BEEN MORE CAREERFOCUSED  ALL I DO IS IMAGINE " +
"OTHER WOMENS LIVES AND WONDER HOW THEY MANAGED IT ALL MORE THAN ANYTHING I AM " +
"PARALYZED BY FEAR I CANT EVEN ADDRESS WHAT PREGNANCY AND CHILDBEARING " +
"THEMSELVES WOULD MEAN TO MY MARRIAGE MY BODY MY HOUSE MY MENTAL HEALTH ETC I " +
"WISH I DID NOT HAVE TO MULTITASK OR JUGGLE ALL THIS I WISH I WAS ALLOWED TO " +
"JUST BE A WOMAN WHO WANTS TO GET PREGNANT I WISH I COULD TRUST MYSELF TO FIGURE " +
"IT ALL OUT I WISH I COULD STOP JUDGING MYSELF I WISH I HAD EVEN AN INKLING AS " +
"TO WHICH TO CHOOSE  CAREER OR BABY  HELP  CAREER OR BABY DEAR CAREER OR BABY IT " +
"LOOKS LIKE YOUVE UNKNOWINGLY STUMBLED ON THE MANTRA OF THE WORKING MOTHER AKIN " +
"TO BILL MURRAYS NIHILISTIC RALLYING CRY OF IT JUST DOESNT MATTER FROM MEATBALLS " +
"THE WORKING MOTHER REPEATS TO HERSELF OVER AND OVER THERE IS NO SATISFACTORY " +
"SOLUTION THERE IS NO SATISFACTORY SOLUTION ITS ONE PART THERES NO PLACE LIKE " +
"HOME AND TWO PARTS THERES NO MILK IN THE FRIDGE AND IM ON DEADLINE RELATED " +
"STORIES ASK POLLY CAN I TRUST MY JUDGMENT ABOUT MEN  ASK POLLY CAN I BE FRIENDS " +
"WITH MY EX NOW THAT IM MARRIED  AT THIS VERY MINUTE IN FACT MY HUSBAND IS " +
"ACROSS THE COUNTRY AT A CONFERENCE AND I AM SITTING NEXT TO A PILE OF TEN BOOKS " +
"I NEED TO READ FOR VARIOUS ASSIGNMENTS MY KIDS ARE AT A FRIENDS HOUSE BUT " +
"  THEYLL BE HOME SOON AND THEY WROTE PARK AND TEE PARTY ON THE CALENDAR FOR THE " +
"    DAY SEE THERE IS NO SATISFACTORY SOLUTION GO TO THE PARK AND HAVE A TEA " +
"PARTY AND WORRY ABOUT WORK THE WHOLE TIME OR MAKE THE KIDS PLAY BY THEMSELVES " +
"ALL AFTERNOON AND FEEL LIKE A NEGLECTFUL MOTHER AS A WORKING PARENT YOU OFTEN " +
"FEEL LIKE YOU HAVE TO CHOOSE BETWEEN NEGLECTING YOUR CAREER OR SPENDING TOO " +
"LITTLE TIME WITH YOUR KIDS YOURE ALWAYS BURNING THE CANDLE AT BOTH ENDS PISSING " +
"INTO THE WIND AND ROBBING THE CAT TO PAY THE DOG BUT  CASTING ASIDE THE " +
"FEMINIST LAYERS OF THIS ISSUE FOR A MOMENT  THIS STATE OF AFFAIRS IS NOT " +
"  IMPOSSIBLE AND TERRIBLE AND LAMENTABLE NECESSARILY ITS SIMPLY WHAT IT FEELS " +
"LIKE TO HAVE IT ALL  BECAUSE HAVING IT ALL BY ITS VERY NATURE IMPLIES THAT YOU " +
"HAVE A LOT MORE THAN YOU CAN HANDLE WHO CAN HANDLE IT ALL ANYWAY ALL IS A WHOLE " +
"FUCKING HELL OF A LOT IF YOU HAVE SOME KIDS AND A CAREER AND YOU DONT HAVE BIG " +
"  PILES OF CASH AND A STAFF OF FIVE YOURE GOING TO BE BUSIER AND MORE " +
"CONFLICTED THAN YOUVE EVER BEEN BEFORE OKAY EVEN WITH THE MONEY AND THE STAFF " +
"YOULL BE BUSY AND CONFLICTED  SO WHY NOT JUST SAY FUCK THE CAREER AND JUST HAVE " +
"THE BABY WHY NOT JUST SAY TO HELL WITH KIDS AND PURSUE A CAREER YOU LOVE " +
"INSTEAD WHY TRY TO HAVE IT ALL AT ALL HERES WHY BECAUSE HAVING A GREAT CAREER " +
"IS THE BEST AND HAVING BABIES IS FUCKING INCREDIBLE AND HAVING BOTH IS AMAZING " +
"AND NO IM NOT KIDDING NOT EVEN A LITTLE BIT  CHOOSE BOTH CHOOSE THE CAREER AND " +
"CHOOSE THE BABY DONT PUT OFF ONE FOR THE OTHER CHOOSE BOTH NOW AND LATER AND " +
"  ACCEPT THAT YOULL BE JUGGLING FOR YEARS NO MATTER WHAT YOU DO EVEN IF YOU " +
"    NEVER HAVE A CAREER YOURE GOING TO FEEL LIKE YOURE JUGGLING PARENTS JUGGLE " +
"WHY NOT JUGGLE THINGS YOU LOVE SURE YOULL HAVE TO WORK HARD AND MAKE SOME " +
"SACRIFICES ACCEPT IT AND MOVE FORWARD  BECAUSE EVEN THOUGH YOU KEEP SAYING YOU " +
"DONT WANT TO WORK YOU JUST WANT TO HAVE BEAUTIFUL BABIES I READ THAT AS THE " +
"TEMPORARY SENTIMENT OF SOMEONE WHOS TRAPPED IN A JOB SHE HATES I KNOW PLENTY OF " +
"HAPPY HOUSEWIVES BUT THEYRE NATURALLY LOWKEY PEOPLE FOR THE MOST PART NOT " +
"  PEOPLE WHO SEND RAMBLING THREEPAGE LETTERS TO ADVICE COLUMNISTS BASED ON THE " +
"RACING ANXIOUS RHYTHMS OF YOUR LETTER I REALLY DONT THINK YOU FIT THE " +
"HAPPYHOUSEWIFE PROFILE I THINK YOURE IMAGINING THAT DOWNSHIFTING TO RAISE " +
"BEAUTIFUL BABIES IS A LITTLE BIT LIKE AN EXTENDED VACATION A LITTLE " +
"BREASTFEEDING AND COOING AND ONE GORGEOUS PHOTO OP AFTER ANOTHER IF YOUR " +
"  HUSBAND AND MAYBE AN INLAW ARE AROUND AFTER THE BABY IS BORN STRONGLY " +
"RECOMMEND YOUR MATERNITY LEAVE WILL FEEL LUXURIOUS AND RELAXING BUT DAYTODAY " +
"LIFE AT HOME ALONE WITH AN INFANT IS A PARTICULAR KIND OF CHALLENGE ONE THAT " +
"BASED ON MY PERSONAL OBSERVATIONS SUITS MAYBE ONE OUT OF TEN WOMEN WELL " +
"PERSONALLY I LOVE BABIES A LOT BUT I NEED A LITTLE BIT OF TIME EACH DAY TO " +
"THINK AND WRITE AND BE ALONE AND GET SHIT DONE ITS EASY ENOUGH TO GET OBSESSED " +
"WITH HAVING BABIES WHEN YOU LOVE YOUR HUSBAND LOVE YOUR HOUSE HATE YOUR JOB AND " +
"DONT KNOW WHAT ELSE YOUD WANT TO DO INSTEAD BUT I WOULD STRONGLY RECOMMEND THAT " +
"  YOU NOT MAKE THE CHOICE TO HAVE A BABY SOONER SIMPLY BECAUSE IT OFFERS THE " +
"BEST ONEWAY TICKET AWAY FROM CORPORATE PURGATORY  YOU NEED TO ADDRESS YOUR " +
"CAREER SITUATION SEPARATELY INSTEAD OF THROWING IT INTO THE MIX OF HAVING KIDS " +
"AND THEN SUMMING IT ALL UP AS IMPOSSIBLE YOU ALREADY KNOW FOR A FACT THAT YOU " +
"  DONT WANT A JOB IN CORPORATE BANKING THATS NEVER GOING TO CHANGE I WOULD MAKE " +
"A PLAN TO QUIT WITHIN THE NEXT YEAR I WOULD MAKE A PLAN TO SAVE MONEY AND SCALE " +
"BACK YOUR SPENDING I WOULD COMMIT TO EXERCISING ONCE A DAY TO KEEP YOUR SPIRITS " +
"UP AND TACKLE YOUR ANXIOUS NATURE I WOULD PUT YOUR IDEAS ABOUT YOUR NEW CAREER " +
"ON PAPER I WOULD TALK TO PEOPLE WHO DO WHAT YOU WANT TO DO FOR A LIVING I WOULD " +
"  TAKE ACTION AND YES MAYBE DEDICATE NIGHTS AND WEEKENDS TO FIGURING IT OUT " +
"OKAY AND WHAT IS THIS HORSE SHIT ABOUT KEEPING YOUR JOB FOR THE BANKING PERKS " +
"  THE FACT THAT YOU EVEN PUT THOSE WORDS TO PAPER TELLS ME THAT YOU ARENT " +
"SEEING CLEARLY DO YOU WANT TO WAKE UP FIVE YEARS FROM NOW AND SAY TO YOURSELF " +
"WELL I WAS MISERABLE FOR A LONG TIME BUT FUCK THOSE BANKING PERKS WERE REALLY " +
"  SOMETHING  YOU HAVE TO GET VERY CALM AND PRACTICAL AND YOU HAVE TO MOVE " +
"FORWARD ONE STEP AT A TIME WITHOUT PANICKING YOU KNOW WHAT YOU WANT ALREADY YOU " +
"WANT A CAREER YOU WANT A BABY AND YOU WANT A JOB YOU CAN DO FROM HOME YOU WANT " +
"A HOMEBASED BUSINESS YOU ALSO MENTION BROADCAST JOURNALISM BUT HONESTLY THAT " +
"PARTICULAR ROUTE SOUNDS LIKE A STRESSFUL CRAPSHOOT FOR YOU GIVEN YOUR STRONG " +
"  DESIRE TO HAVE A FAMILY SOON FOUR YEARS OF SCHOOL AND THEN YOURE EITHER A " +
"LOCAL ANCHOR OR YOURE TRAVELING FOR STORIES OR YOURE SITTING AT HOME WITH " +
"  BABIES LOOKING AT YOUR DEGREE ON THE WALL THIS IS OBVIOUSLY MY PERSONAL TAKE " +
"ON IT BUT MOST PEOPLE WONT GIVE YOU ANY KIND OF OPINION ON A JOB YOU MIGHT WANT " +
"TO DO SO IM GOING TO STEP UP TO THE PLATE AND BE THAT ASSHOLE THIS DOESNT SOUND " +
"LIKE A GOOD FIT FOR YOU GIVEN YOUR CURRENT DESIRE FOR A GOOD WORKLIFE BALANCE " +
"  NOR DOES IT SOUND LIKE SOME KIND OF LIFELONG DREAM YOULL DIE IF YOU DONT " +
"    PURSUE IF IT IS THEN DISREGARD EVERYTHING IVE WRITTEN HERE AND FUCKING GO " +
"      FOR IT  ITS UNDERSTANDABLE BUT ALSO A BIG MISTAKE TO READ  ARTICLES ABOUT " +
"        HOW WOMEN CANT HAVE IT ALL AND THEN THINK YOURSELF INTO A DEEP DARK " +
"HOLE OVER HOW YOULL EVER PULL IT OFF IN THIS CASE  AND SO MANY OTHERS  FIXATING " +
"ON THE BIG PICTURE WILL ONLY DRAG YOU UNDER TO BE CLEAR I LOVE ANNEMARIE " +
"SLAUGHTERS ARTICLE ON THIS SUBJECT BECAUSE I THINK SHE POINTS OUT A LOT OF THE " +
"BULLSHIT ASSUMPTIONS SO MANY OF US HOLD DEAR THAT CHILD CARE IS SOMEHOW A " +
"WOMENS ISSUE AND NOT A PARENTS ISSUE FOR EXAMPLE THE HYSTERIA AROUND THESE " +
"  CHOICES IS OFF THE CHARTS PEOPLE WILL SAY OH LOTS OF PARENTS REGRET HAVING " +
"KIDS THEY JUST DONT TELL YOU ABOUT IT OR WORKING WOMEN ARE MISERABLE OR KIDS " +
"WITH WORKING MOTHERS ARE ANXIOUS AND UNHAPPY OR KIDS WILL DESTROY YOUR CAREER " +
"OR IF YOU CANT GIVE YOUR CHILDREN EVERY OUNCE OF YOUR ENERGY YOU SHOULDNT HAVE " +
"  KIDS AT ALL OR YOU CANT BE A REAL ARTIST AND HAVE KIDS AND ALL KINDS OF OTHER " +
"COMPLETELY BLACKANDWHITE FEARFUL CONFLICTED NONSENSE IM NOT INSIDE OTHER " +
"PEOPLES HEADS BUT THE CLOSE FRIENDS I HAVE WHO ARE IN GOOD MARRIAGES LIKE YOURS " +
"AND HAVE KIDS AND ENGAGING CAREERS ARE SOME OF THE HAPPIEST PEOPLE I KNOW  SO " +
"LISTEN YOULL DEAL WITH PROBLEMS AS THEY COME UP THE PROBLEMS COME UP EVERY DAY " +
"AND THE PROBLEMS CHANGE EVERY MILLISECOND BABIES AND TODDLERS ARE TWO DIFFERENT " +
"SPECIES OF ANIMAL AND SCHOOLKIDS ARE IN SOME WAYS MORE HIGHMAINTENANCE THAN " +
"BABIES OR TODDLERS THERE WILL BE MANY CHALLENGES ALONG THE WAY AND THERE WILL " +
"BE PLENTY OF SOLUTIONS TOO SOME OF THEM MIGHT EVEN FEEL SATISFACTORY FOR A " +
"  SECOND OR TWO  ONE OTHER THING BEING PREGNANT MAKES YOU IRRITABLE AND " +
"AMBITIOUS AT THE SAME TIME USE THAT ENERGY TO FUEL YOUR NEW BUSINESS ONCE YOU " +
"STOP FEELING HUNGOVER AROUND THE CLOCK YOURE GOING TO WANT TO CONQUER NEW " +
"TERRAIN AND STRANGLE ANYONE WHO TELLS YOU TO RELAX WITH YOUR BARE HANDS DURING " +
"MY FIRST PREGNANCY I CHANNELED THIS ENERGY INTO WRITING SCATHING TV REVIEWS " +
"DURING MY SECOND PREGNANCY I WROTE A BOOK I COULDNT SLEEP SO I WOKE UP AT  IN " +
"THE MORNING AND WROTE I KNOW THIS VISION IS JUST AS IDEALISTIC AND MISLEADING " +
"AS ANY OTHER AND EVERY STORY IS DIFFERENT I JUST WANT YOU TO KNOW THAT I " +
"PERSONALLY WAS AMAZED AT HOW MUCH MORE ENERGETIC I WAS AS A PREGNANT LADY I " +
"OFTEN SAID TO MY HUSBAND WHATEVER THIS DRUG IS I WISH I COULD TAKE IT FOREVER " +
"THEN I PROBABLY SAID SOMETHING LIKE GO GET ME SOME NACHOS OR ILL BUST YOUR " +
"KNEES IN WITH THIS TIRE IRON SAVE NOW TO HIRE A NANNY IF YOUR HUSBAND CANT TAKE " +
"  PATERNITY LEAVE AND DONT SAY WOMEN HAVE BEEN DEALING WITH INFANTS ON THEIR " +
"OWN FOR CENTURIES WOMEN HAVE BEEN TREATED LIKE CHATTEL FOR CENTURIES TOO LIVING " +
"  IN A VILLAGE FULL OF WOMEN IS A FAR CRY FROM HAUNTING A HOUSE IN THE SUBURBS " +
"WITH AN ADORABLE LITTLE ALIEN WHO TURNS INTO A SCREAMING BANSHEE FOR MYSTERIOUS " +
"  REASONS EVERY FEW HOURS FIND A WAY TO GET HELP FIND A WAY LOTS OF HELP THE " +
"BIGGEST MISTAKE NEW MOTHERS MAKE IS TELLING THEMSELVES I SHOULD BE ABLE TO " +
"HANDLE THIS ALL BY MYSELF BULLSHIT YOU SHOULD DO WHAT YOU NEED TO DO TO TAKE " +
"CARE OF YOURSELF AND NOT SEND YOURSELF OFF A FUCKING CLIFF EMOTIONALLY BABIES " +
"HAVE NO USE FOR PARENTS WHOSE NERVES ARE FRAYED TO THE POINT OF NO RETURN AND " +
"  BABIES ARE BIOLOGICALLY DESIGNED TO FRAY NERVES LIKE A MOTHERFUCKER BECAUSE " +
"IT GUARANTEES THAT THEIR NEEDS WILL GET MET  SO LOOK I COULD WRITE AN ENTIRE " +
"BOOK ON THIS SUBJECT  A TERRIBLE HIGHLY SUBJECTIVE BOOK MOST PARENTS COULD ALL " +
"I WANT TO TELL YOU IS THAT YOU CAN HAVE A BABY AND HAVE A CAREER AND YES I " +
"THINK ITS VERY SMART TO WANT BOTH AND TO GO FOR BOTH SHOULD YOU WAIT TO HAVE " +
"  THE BABY MAYBE SET UP THE BUSINESS AND GET IT GOING FIRST YES I WOULDNT WAIT " +
"THAT LONG  EITHER TO QUIT OR TO START YOUR BUSINESS OR TO HAVE BABIES I DONT " +
"THINK YOU CAN BE INSANELY STRATEGIC ABOUT THE TIMING OF KIDS ITS GREAT TO HAVE " +
"A GOOD MARRIAGE AND KNOW WHAT YOU WANT WHEN YOURE YOUNG AND FULL OF STEAM BUT " +
"FOR THOSE WHO ARENT THERE YET IM  AND I HAVE A YEAROLD AND THATS GREAT TOO MY " +
"  HUSBAND AND I BOTH HAVE ESTABLISHED FLEXIBLE CAREERS AND THAT MAKES PARENTING " +
"FEEL MUCH LESS EXHAUSTING AND LONELY THERE ARE ADVANTAGES AND DISADVANTAGES TO " +
"EVERY TIMELINE  BOTTOM LINE I WAS SO FEARFUL BUT THROWING MY ENERGY INTO BOTH " +
"MY KIDS AND MY CAREER TURNED OUT SO MUCH BETTER THAN I EVER THOUGHT IT COULD " +
"AND I BECAME MUCH MORE FOCUSED AND AMBITIOUS AFTER I HAD KIDS I VALUED MY TIME " +
"MORE I USED MY TIME MORE WISELY ALL OF THE TIME I USED TO SPEND QUESTIONING " +
"MYSELF AND WORRYING ABOUT THE BIG PICTURE IS NOW SPENT DOING DISHES AND FOLDING " +
"LITTLE DRESSES A LOT OF THE WORKING MOTHERS I KNOW FEEL THE SAME WAY  YOURE " +
"SMART AND AMBITIOUS AND YOURE SENSITIVE TO FEELING LIKE YOURE WASTING YOUR TIME " +
"YOU SOUND LIKE SOMEONE WHO WILL NEED TO WORK AT LEAST PARTTIME FOR THE REST OF " +
"  HER LIFE PARTICULARLY ONCE YOU FIND SOMETHING THAT YOU REALLY ENJOY DONT " +
"CONFUSE YOUR CURRENT LAME JOB WITH THE FEELING OF WORKING AT SOMETHING THAT " +
"FEELS GRATIFYING TO YOU WHERE YOU COMPLETE PROJECTS FROM START TO FINISH " +
"INSTEAD OF JUST PUNCHING A CLOCK EVERY DAY IMAGINE A FULL LIFE AND BE TRUE TO " +
"THAT VISION DEFEND IT AND PUT FEAR ASIDE YOU HAVE ONE PERSON WITH A STEADY JOB " +
"IN THE HOUSE DONT PANIC LOOK CLOSELY AT YOUR BUDGET AND MAKE IT WORK AND GO " +
"READ THE TWOINCOME TRAP WHILE YOURE AT IT YOU CAN HAVE IT ALL YOU MAY HAVE TO " +
"  ADJUST THE PARTICULARS OF IT BUT TRUST ME ALL IS WHAT YOU WANT ITS EXHAUSTING " +
"AND ITS A BALANCING ACT AND ITS WAY TOO MUCH FOR ANYONE TO HANDLE EVER THATS " +
"  ALSO WHATS SO GRATIFYING ABOUT IT " +
"";

var NIHILISM = "ALTHOUGH NIHILISM IS OFTEN THOUGHT OF AS A VAGUE CONCEPT RELEGATED TO THE ARENA OF PHILOSOPHY OR PERHAPS AS THE UNAVOIDABLE CONCLUSION TO THOUGHT NIHILISM DOES HAVE A STRONG HISTORICAL BACKGROUND THAT DESERVES GREATER THE MOST SIGNIFICANT MANIFESTATION OF NIHILISM IN RECENT HISTORY ALSO COINCIDES WITH ITS MOST ACTIVE AND ORGANIZED EXPRESSION THAT OF THE RUSSIAN NIHILIST REVOLUTIONARIES WHO ROSE TO PROMINENCE IN THE THE RUSSIAN NIHILISTS THE RUSSIAN WORD FOR NIHILIST IS NIGILIST TEND TO BE ASSOCIATED WITH VIOLENCE REVOLUTION AND TERRORIST ACTS SUCH AS THE ASSASSINATION OF CZAR ALEXANDER II BY THE WILL OF THE PEOPLE BY ILYA REPIN BUT ALTHOUGH VIOLENT ACTS GET RECORDED IN THE HISTORY BOOKS OFTEN THE LASTING IMPACT IS CARRIED THROUGH IDEAS AND THE RUSSIAN NIHILISTS WERE INTRIGUING IN THIS REGARD FOR THEIR HISTORY IS LIKE THAT OF AN ICEBERG ONLY A SMALL PORTION OF THEIR TOTAL CHARACTER IS READILY INDEED MUCH OF THE VIOLENT ACTS ASSOCIATED WITH THE ATTEMPTED OVERTHROW OF THE MONARCHY OCCURRED UNDER THE AUSPICES OF OTHER GROUPS SUCH AS ANARCHISTS MARXISTS AND NARODNICHESTVO POPULISTS IN THE RATHER THAN THOSE DIRECTLY ASSOCIATED WITH THE NIHILISTS THEMSELVES WHO WERE MUCH MORE COMPLEX THAN THE TERRORIST LABEL ATTACHED TO THEM BY AUTOCRATIC NIHILISM WAS NOT SO MUCH A CORPUS OF FORMAL BELIEFS AND PROGRAMS LIKE POPULISM LIBERALISM MARXISM AS IT WAS A CLUSTER OF ATTITUDES AND SOCIAL VALUES AND A SET OF BEHAVIORAL DRESS FRIENDSHIP IN SHORT IT WAS AN IN ORDER TO UNDERSTAND WHO THE RUSSIAN NIHILISTS WERE WE FIRST HAVE TO UNDERSTAND WHAT THEY FOUGHT AGAINST AND EUROPE IN THE CENTURY WAS A TIME OF DRAMATIC CHANGES POLITICAL ECONOMIC AND INDUSTRIALIZATION CREATED FANTASTIC WEALTH DISPARITIES AND ENTIRELY NEW CLASSES OF PEOPLE AS THE OLD ARISTOCRATIC POWER SYSTEM TRANSFORMED INTO A PLUTOCRATIC CITIES GREW RAPIDLY AND TRADITIONAL AGRARIAN LIFESTYLES WERE DECIMATED IN FAVOR OF THE CRAMPED URBAN LIFE OF WAGE IMPERIAL RUSSIA EXPERIENCED MANY OF THESE DIFFICULT CHANGES BUT EVENTS OFTEN TOOK ON A MORE EXTREME CHARACTER THAN THAT OF WESTERN EUROPE AND SOCIAL DEVELOPMENT FOR RUSSIA HAS ALWAYS BEEN BOTH PAINFUL AND PUTTING A PROPAGANDIST UNDER ARREST BY ILYA REPIN OF THE WISER RUSSIAN MONARCHS REALIZED THAT THEIR SYSTEM OF SERFDOM WITH A SOCIAL STRUCTURE OF THE VERY FEW EXISTING ON THE BACKS OF THE VERY MANY WAS NOT SUSTAINABLE AND WOULD END IN BLOODY REBELLION SOONER OR THE PROBLEM WAS IMPLEMENTING REFORMS THAT WERE BOTH EFFECTIVE AND POLITICALLY BY THE MIDDLE OF THE CENTURY THE FORCES OF STATE REPRESSION COUPLED WITH THE LONGEVITY OF THE PROBLEM HAD ALREADY CREATED SUCH AN INTOLERABLE SITUATION THAT FIXING THE SYSTEM THROUGH REFORM WAS ESSENTIALLY THE ONLY REASONABLE ANSWER TO THIS KIND OF SITUATION IS THE ONLY WAY TO LIVE IS TO RUSSIA HAD BECOME A STIFLING BACKWARDS COUNTRY RUN BY A RULING ELITE GROWN FABULOUSLY WEALTHY THROUGH RAMPANT NATURAL RESOURCE THE RUSSIAN GOVERNMENT HAD BECOME COMPLETELY DISCONNECTED FROM ITS SUBJECTS AND NEW INFORMATION AND NEW IDEAS WERE IMPOSSIBLE TO PREVENT FROM SEEPING INTO THE COUNTRY FROM THE HEATED AND BUBBLING SOCIAL SCENE IN WESTERN EVEN A BRUTAL AND VIOLENT COULD NOT STOP THE NIHILISTS OTHER DEDICATED REVOLUTIONARIES OR THE INEVITABLE OUTCOME OF THE JEWEL ENCRUSTED FABERGE EGGS WERE AN EMBLEMATIC EXPRESSION OF LATE CENTURY IMPERIAL RUSSIAN WEALTH AND A GROSSLY DISTORTED SOCIETY WHERE THE MONARCHY COULD COMMISSION DOZENS OF THESE EGGS WHILE THE GENERAL PUBLIC WORKED AND STARVED TO THE HEART OF RUSSIAN NIHILISM WAS ABOUT BREAKING WITH THE FAILURES OF THE PAST AND ABOUT CRAFTING A NEW THIS WAS THE MEANING OF THE FATHERS AND SONS PHRASE USED AT THE TIME AND REMEMBERED TODAY IN TURGENEVS NOVEL OF THE SAME WHEREAS THE FATHERS GREW UP ON GERMAN IDEALISTIC PHILOSOPHY AND ROMANTICISM IN GENERAL WITH ITS EMPHASIS ON THE METAPHYSICAL RELIGIOUS AESTHETIC AND HISTORICAL APPROACHES TO REALITY THE SONS LED BY SUCH YOUNG RADICALS AS NICHOLAS CHERNYSHEVSKY NICHOLAS DOBROLIUBOV AND DMITRII PISAREV HOISTED THE BANNER OF UTILITARIANISM POSITIVISM MATERIALISM AND ESPECIALLY NIHILISM AND ALSO IN LARGE PART REALISM PARTICULARLY CRITICAL REALISM MEANT ABOVE ALL ELSE A FUNDAMENTAL REBELLION AGAINST ACCEPTED VALUES AND AGAINST ABSTRACT THOUGHT AND FAMILY CONTROL AGAINST LYRIC POETRY AND SCHOOL DISCIPLINE AGAINST RELIGION AND THE EARNEST YOUNG MEN AND WOMEN OF THE WANTED TO CUT THROUGH EVERY POLITE VENEER TO GET RID OF ALL CONVENTIONAL SHAM TO GET TO THE BOTTOM OF WHAT THEY USUALLY CONSIDERED REAL AND WORTHWHILE INCLUDED THE NATURAL AND PHYSICAL SCIENCES FOR THAT WAS THE AGE WHEN SCIENCE CAME TO BE GREATLY ADMIRED IN THE WESTERN WORLD SIMPLE AND SINCERE HUMAN RELATIONS AND A SOCIETY BASED ON KNOWLEDGE AND REASON RATHER THAN IGNORANCE PREJUDICE EXPLOITATION AND THIS WAS ABOUT THE DESTRUCTION OF IDOLS ABOUT BURNING THE DEAD WOOD OF AND THE RUSSIAN NIHILISTS WERE QUITE REVOLUTIONARY ESPECIALLY GIVEN THE CONTEXT OF THE TIME AND LOCATION THEY EXISTED IN FOR THEY INCLUDE SECTIONS OF THE POPULATION THAT HAD LITTLE IF ANY REPRESENTATION WOMEN FOR EXAMPLE PLAYED A KEY ROLE AND INCLUDED SOME OF THE MOST MOTIVATED AND CHARISMATIC CHARACTERS OF THE TIME PERIOD LIKE VERA FIGNER AND SOPHIA THE FEMINISTS WANTED TO CHANGE PIECES OF THE WORLD THE NIHILISTS WANTED TO CHANGE THE WORLD ITSELF THOUGH NOT NECESSARILY THROUGH POLITICAL THE RUSSIAN WORD FOR A FEMALE NIHILIST IS ITS IMPORTANT TO POINT OUT THAT THE NIHILIST ETHOS OF THE TIME WAS PRIMARILY INDIVIDUALISTIC AND NOT ALWAYS POLITICALLY SOME RADICAL NIHILIST ATTITUDES PRECLUDED IDEOLOGICAL OR POLITICAL NIHILISM EMANCIPATED THE YOUNG RUSSIAN RADICALS FROM ANY ALLEGIANCE TO THE ESTABLISHED ORDER IT WAS TO REPEAT A POINT INDIVIDUAL RATHER THAN SOCIAL BY ITS VERY NATURE AND LACKED A POSITIVE PROGRAM BOTH PISAREV AND TURGENEVS HERO BAZAROV DIED CLOTHING ATTITUDE COMMUNICATIONS STYLE ALL WERE PORTIONS OF THE NEW NIHILIST THE CLOTHING STYLE SOUGHT FUNCTIONALITY AND USEFULNESS OVER FRIVOLOUS THE REVOLT IN THE DRESS OF THE NIGILISTKA WENT SOMETHING LIKE ONE OF THE MOST INTERESTING AND WIDELY REMARKED FEATURES OF THE NIGILISTKA WAS HER PERSONAL DISCARDING THE MUSLIN RIBBONS FEATHERS PARASOLS AND FLOWERS OF THE RUSSIAN LADY THE ARCHETYPICAL GIRL OF THE NIHILIST PERSUASION IN THE WORE A PLAIN DARK WOOLEN DRESS WHICH FELL STRAIGHT AND LOOSE FROM THE WAIST WITH WHITE CUFFS AND COLLAR AS THE ONLY THE HAIR WAS CUT SHORT AND WORN STRAIGHT AND THE WEARER FREQUENTLY ASSUMED DARK NIGILISTKA FASHION WAS ABOUT MORE THAN JUST JUVENILE REBELLION AGAINST BOURGEOISIE FASHION BECAUSE INSTEAD OF SIMPLY CONTRADICTING ESTABLISHED FORMS IT WENT ON TO CREATE ITS OWN WAS THE REASON BEHIND MUCH OF MACHINERY OF SEXUAL ATTRACTION THROUGH OUTWARD APPEARANCE THAT LED INTO SLAVERY WAS DISCARDED BY THE NEW WOMAN WHOSE NIHILIST CREED TAUGHT HER THAT SHE MUST MAKE HER WAY WITH KNOWLEDGE AND ACTION RATHER THAN FEMININE EVEN DEEPER THAN CHANGES IN SUPERFICIAL APPEARANCE EXISTED A NEW AND QUITE PROFOUND REALIZATION FOR THE NIGILISTKA UNDERSTOOD THAT LIFE HAD TO BE DEFINED INTERNALLY AND NOT SOLELY BY EXTERNAL AUTHORITIES OR TO ESTABLISH HER IDENTITY SHE NEEDED A CAUSE OR A PATH RATHER THAN JUST A AN INTERESTING DEPARTURE ALSO OCCURRED IN COMMUNICATIONS TYPICAL NIGILISTKA LIKE HER MALE COMRADE REJECTED THE CONVENTIONAL HYPOCRISY OF INTERPERSONAL RELATIONS AND TENDED TO BE DIRECT TO THE POINT OF SEVERE TIMES CALL FOR SEVERE SEEING THEIR EFFORTS AT SOCIAL CHANGE ONLY BEING MET WITH POLICE BRUTALITY AND INCREASING REPRESSION BY DESPOTIC AUTHORITY THE REVOLUTIONARIES REASSESSED THEIR PETER TKACHEV AND SERGEI NECHAYEV WERE TWO THAT FELT SEVERE TIMES CALL FOR SEVERE MEASURES THE REVOLUTION WAS ONLY GETTING SEVERAL YEARS OF REVOLUTIONARY CONSPIRACY TERRORISM AND ASSASSINATION THE FIRST INSTANCES OF VIOLENCE OCCURRED MORE OR LESS SPONTANEOUSLY SOMETIMES AS COUNTERMEASURES AGAINST BRUTAL POLICE THUS EARLY IN VERA ZASULICH SHOT AND WOUNDED THE MILITARY GOVERNOR OF PETERSBURG GENERAL THEODORE TREPOV WHO HAD ORDERED A POLITICAL PRISONER TO BE A JURY FAILED TO CONVICT HER WITH THE RESULT THAT POLITICAL CASES WERE WITHDRAWN FROM REGULAR JUDICIAL BUT BEFORE LONG AN ORGANIZATION EMERGED WHICH CONSCIOUSLY PUT TERRORISM AT THE CENTER OF ITS THE CONSPIRATORIAL REVOLUTIONARY SOCIETY LAND AND FREEDOM FOUNDED IN SPLIT IN INTO TWO THE BLACK PARTITION OR TOTAL LAND REPARTITION WHICH EMPHASIZED GRADUALISM AND PROPAGANDA AND THE WILL OF THE PEOPLE WHICH MOUNTED AN TERRORISTIC OFFENSIVE AGAINST THE MEMBERS OF THE WILL OF THE PEOPLE BELIEVED THAT BECAUSE OF THE HIGHLY CENTRALIZED NATURE OF THE RUSSIAN STATE A FEW ASSASSINATIONS COULD DO TREMENDOUS DAMAGE TO THE REGIME AS WELL AS PROVIDE THE REQUISITE POLITICAL INSTRUCTION FOR THE EDUCATED SOCIETY AND THE THEY SELECTED THE EMPEROR ALEXANDER II AS THEIR CHIEF TARGET AND CONDEMNED HIM TO WHAT FOLLOWED HAS BEEN DESCRIBED AS AN EMPEROR HUNT AND IN CERTAIN WAYS IT DEFIES THE EXECUTIVE COMMITTEE OF THE WILL OF THE PEOPLE INCLUDED ONLY ABOUT THIRTY MEN AND WOMEN LED BY SUCH PERSONS AS ANDREW ZHELIABOV WHO CAME FROM THE SERFS AND SOPHIA PEROVSKAIA WHO CAME FROM RUSSIAS HIGHEST ADMINISTRATIVE CLASS BUT IT FOUGHT THE RUSSIAN AFTER THE ASSASSINATION OF THE TSAR SOME BEGAN TO QUESTION THE STRATEGIC USEFULNESS OF THE SPIRALING VIOLENCE BUT FEW ALTERNATIVES EXISTED IN THE OPPRESSIVE MILIEU OF IMPERIAL SUBSEQUENT MONARCHS ALEXANDER III AND NICHOLAS II ONLY BECAME MORE REACTIONARY AND WHILE SIMULTANEOUSLY VOIDING EVEN MINIMAL PUBLIC MURDER AND THE GIBBET CAPTIVATED THE IMAGINATION OF OUR YOUNG AND THE WEAKER THEIR NERVES AND THE MORE OPPRESSIVE THEIR SURROUNDINGS THE GREATER WAS THEIR SENSE OF EXALTATION AT THE THOUGHT OF REVOLUTIONARY VERA FIGNER";

var IGNORES = ['', ' ', '\n'];

var Corpus = function(corpus) {
  var _learn = function(state, next_word) {
    var memory = state.memory,
        prev_word = state.prev_word;

    if (next_word in IGNORES) {
      return state;
    }

    if (!memory[prev_word]) {
      memory[prev_word] = [];
    }

    memory[prev_word].push(next_word);

    return {memory: memory, prev_word: next_word};
  };

  corpus = corpus || [FASHION, NIHILISM].join(' ');
  var words = corpus.split(' ');
  this.memory = words.reduce(_learn, {memory: {}, prev_word: ''}).memory;
}

Corpus.prototype.suggest = function() {
  var options = Object.keys(this.memory);
  return options[Math.floor(Math.random() * options.length)];
};

Corpus.prototype.next = function(from) {
  var options = this.memory[from];

  if (!options || !options.length) {
    return this.suggest();
  }

  return options[Math.floor(Math.random() * options.length)];
};

Corpus.prototype.sentence = function() {
  var word = this.suggest();
  var sentence = [];
  var size = Math.round(Math.random() * (5 - 2) + 2);
  for (var x = 0; x < size; x++) {
    word = this.next(word);
    sentence.push(word);
  }

  return sentence.join(' ');
}

Corpus.prototype.challenge = function() {
  return new Challenge(this.sentence());
};
